baseURL = 'https://len-sprague.github.io/PLeW/'
languageCode = 'en-us'
title = 'PLeW'

[params]
  description = 'Interactive multi-dimensional data visualizer'

[markup.goldmark.renderer]
  unsafe = true
