baseURL = 'https://plop-code.github.io/plew/'
languageCode = 'en-us'
title = 'PLeW'

[params]
  description = 'Interactive multi-dimensional data visualizer'

[markup.goldmark.renderer]
  unsafe = true
